
#RubidiumToolkit
[Settings]

	[Settings.Misc]
		"Render Fog" = true

	[Settings."Lighting Settings"]
		"Dynamic TileEntity Lighting" = true
		"Only Update On Position Change" = true
		#Allowed Values: OFF, SLOW, FAST, REALTIME
		"Quality Mode (OFF, SLOW, FAST, REALTIME)" = "REALTIME"
		"Dynamic Entity Lighting" = true

	[Settings."Entity Distance"]
		"Enable Max Distance Checks" = true
		"(BlockEntity) Max Horizontal Render Distance [Squared, Default 64^2]" = 4096
		"(Entity) Max Vertical Render Distance [Raw, Default 32]" = 32
		"(BlockEntity) Max Vertical Render Distance [Raw, Default 32]" = 32
		"(Entity) Max Horizontal Render Distance [Squared, Default 64^2]" = 4096

